spring:
  application:
    name: shop-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-wild-cell-a4eyvtv0-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_fOKHwyjz7Y2C
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shop.demo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080